language: ruby

rvm:
  - 2.0.0
  - 2.1.7
  - 2.2.3

cache: bundler

before_install:
  - sudo apt-get autoremove sqlite3
  - sudo apt-add-repository -y ppa:travis-ci/sqlite3
  - sudo apt-get -y update
  - sudo apt-get install -y sqlite3=3.7.15.1-1~travis1
  - gem install bundler -v 1.10.5


script:
  - bundle exec rake test
